language: node_js

os: osx

node_js:
  - "iojs"
  - "7"

branches:
  only:
    - "master"

before_deploy: ./build.sh

deploy:
  - provider: pages
    github-token: $GITHUB_TOKEN
    local-dir: "./out"
    skip_cleanup: true
    on:
      branch: master
  - provider: releases
    api_key: $GITHUB_TOKEN
    file:
      - "./application/FinanceList-Desktop-win32-x64.zip"
      - "./application/FinanceList-Desktop-linux-x64.zip"
      - "./application/FinanceList-Desktop-mac-x64.dmg"
    skip_cleanup: true